### ISSUE TITLE
Support postcss.config.js standard format

### ISSUE THREAD

**Issue by ryuran** [jeffjewiss/broccoli-postcss#392]
Hello

Currently broccoli-postcss support `plugins` option as an `Array`.
But postCSS standard config for webpack postcss-loader use an `Object`.

https://github.com/michael-ciniawsky/postcss-load-config#postcssrcjs-or-postcssconfigjs

So if we respect postCSS documentation about the config file, it fail with `broccoli-postcss`

```
- stack: TypeError: opts.plugins.forEach is not a function
    at PostcssFilter.processString (…/node_modules/broccoli-postcss/index.js:54:16)
    at resolve (…/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/strategies/default.js:18:19)
    at initializePromise (…/node_modules/broccoli-postcss/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (…/node_modules/broccoli-postcss/node_modules/rsvp/dist/rsvp.js:1017:35)
    at Object.processString (…/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/strategies/default.js:17:18)
    at Processor.processString (…/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/processor.js:24:27)
    at resolve (…/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/index.js:433:16)
    at initializePromise (…/node_modules/broccoli-postcss/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (…/node_modules/broccoli-postcss/node_modules/rsvp/dist/rsvp.js:1017:35)
    at invoke (…/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/index.js:432:10)
```
Maybe we should use `postcss-load-config` module

**Comment by jeffjewiss** [comment]
Hi, the API for Postcss is for plugins to be an array, as found in the docs here: https://api.postcss.org/Processor.html

The "postcss-load-config" package you referenced converts a plugins object into an array:
https://github.com/michael-ciniawsky/postcss-load-config/blob/master/src/plugins.js#L42

How are you using `broccoli-postcss` in your application that it's not working? Thanks.

**Comment by jeffjewiss** [comment]
Hi @ryuran, I'm closing this since I haven't heard back in a while. Please let me know if you're still having an issue.

**Comment by ryuran** [comment]
Thanks @jeffjewiss
I converted my object to an array.
